# Generated by Django 5.1.1 on 2026-03-30 03:57

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, validators=[movies.models.validate_youtube_trailer_url]),
        ),
    ]
