# Generated by Django 5.1.1 on 2026-03-31 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_paymentattempt_paymentwebhookevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentattempt',
            new_name='movies_paym_status_db7260_idx',
            old_name='movies_paym_status_72f1bd_idx',
        ),
    ]
