# Generated by Django 5.1.1 on 2026-04-03 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_rename_movies_paym_status_72f1bd_idx_movies_paym_status_db7260_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Seat temporarily reserved during payment'),
        ),
        migrations.AddField(
            model_name='seat',
            name='locked_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the reservation lock was created', null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='locked_by_attempt',
            field=models.ForeignKey(blank=True, help_text='Which payment attempt holds this seat lock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_seats', to='movies.paymentattempt'),
        ),
    ]
